### ISSUE TITLE
MLCube doesn't recognize parameter type on Windows

### ISSUE THREAD

**Issue by aristizabal95** [mlcommons/mlcube#299]
I'm getting an error when I try to run an MLCube while specifying inline parameters. Running the following command
```
> mlcube run --mlcube=C:\Users\aleja\.medperf\localhost_8000\cubes\1\mlcube.yaml --task=prepare --platform=docker data_path="C:\Users\aleja\.medperf\localhost_8000\demo\137950e4e7b8de3baa4a9982c3ebea6a52bd33d3\mock_chexpert" labels_path="C:\Users\aleja\.medperf\localhost_8000\demo\137950e4e7b8de3baa4a9982c3ebea6a52bd33d3\mock_chexpert" output_path="C:\Users\aleja\.medperf\localhost_8000\data\tmp_37184475603348\data" Ptasks.prepare.parameters.input.data_path.opts="ro" Ptasks.prepare.parameters.input.labels_path.opts="ro"
```
Leads to the following error:
```
2023-02-21 08:45:04 ARISTIZABAL95PC mlcube.__main__[37184] ERROR Failed to run MLCube with error code 1.
Traceback (most recent call last):
  File "d:\users\aleja\anaconda3\envs\factored\lib\site-packages\mlcube_docker\docker_run.py", line 188, in run
    mounts, task_args, mounts_opts = Shell.generate_mounts_and_args(self.mlcube, self.task)
  File "d:\users\aleja\anaconda3\envs\factored\lib\site-packages\mlcube\shell.py", line 212, in generate_mounts_and_args
    _generate(params.outputs, IOType.OUTPUT)
  File "d:\users\aleja\anaconda3\envs\factored\lib\site-packages\mlcube\shell.py", line 167, in _generate
    raise ConfigurationError(f"Invalid task: task={task}, param={_param_name}, "
mlcube.errors.ConfigurationError: Invalid task: task=prepare, param=output_path, type=unknown. Type is unknown.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\users\aleja\anaconda3\envs\factored\lib\site-packages\mlcube\__main__.py", line 211, in run
    runner.run()
  File "d:\users\aleja\anaconda3\envs\factored\lib\site-packages\mlcube_docker\docker_run.py", line 193, in run
    raise ExecutionError.mlcube_run_error(
mlcube.errors.ExecutionError: DockerRun runner failed to run MLCube. Error occurred while generating mount points for docker run command (task=prepare). See context for details and check your MLCube configuration file.
ERROR:
        message: DockerRun runner failed to run MLCube.
        description: Error occurred while generating mount points for docker run command (task=prepare). See context for details and check your MLCube configuration file.
        context: {'error': 'Invalid task: task=prepare, param=output_path, type=unknown. Type is unknown.'}
```
The cube I'm testing works fine with Linux and Mac, and I can specify the parameters the same way I did here without any issues

Here's the mlcube manifest file for context:
```yaml
name: MLCommons Chexpert Preprocessor
description: MLCommons cube for preprocessing chexpert-like datasets
authors:
 - {name: "MLCommons Best Practices Working Group"}

platform:
  accelerator_count: 0

docker:
  # Image name.
  image: mlcommons/chexpert-prep:0.1.0
  # Docker build context relative to $MLCUBE_ROOT. Default is `build`.
  build_context: "../project"
  # Docker file name within docker build context, default is `Dockerfile`.
  build_file: "Dockerfile"

tasks:
  prepare:
    parameters:
      inputs: {data_path: CheXpert-v1.0-small, labels_path: CheXpert-v1.0-small/valid.csv, parameters_file: parameters.yaml}
      outputs: {output_path: data/}
  sanity_check:
    parameters:
      inputs: {data_path: data/, parameters_file: parameters.yaml}
  statistics:
    parameters:
      inputs: {data_path: data/, parameters_file: parameters.yaml}
      outputs: {output_path: {type: file, default: statistics.yaml}}
```

**Comment by sergey-serebryakov** [comment]
Fixed in #301.
